cache:
  isprod: false
  scheduled:
    cron: "-"
    shedlock-lock-at-most-for: PT10M
integration:
  case-management:
    base-url: http://localhost:${wiremock.server.port}/casemanagement
  citizen:
    base-url: http://localhost:${wiremock.server.port}/citizen
  open-e:
    base-url: http://localhost:${wiremock.server.port:}/opene
    password: somePassword
    username: someUsername
  party:
    base-url: http://localhost:${wiremock.server.port}/party
  support-management:
    base-url: http://localhost:${wiremock.server.port}/supportmanagement

spring:
  main:
    banner-mode: 'off'
  flyway:
    enabled: true
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6.4:///
  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          schema-generation:
            script:
              append: false
      jakarta:
        persistence:
          schema-generation:
            create-source: metadata
            database:
              action: update
            scripts:
              action: create
              create-target: target/database/generated-schema.sql
  security:
    oauth2:
      client:
        provider:
          citizen:
            token-uri: http://localhost:${wiremock.server.port:}/token
          case-management:
            token-uri: http://localhost:${wiremock.server.port:}/token
          party:
            token-uri: http://localhost:${wiremock.server.port:}/token
          support-management:
            token-uri: http://localhost:${wiremock.server.port:}/token
        registration:
          citizen:
            client-id: the-client-id
            client-secret: the-client-secret
          case-management:
            client-id: the-client-id
            client-secret: the-client-secret
          party:
            client-id: the-client-id
            client-secret: the-client-secret
          support-management:
            client-id: the-client-id
            client-secret: the-client
