cache:
  isprod: true
  scheduled:
    cron: "-"
    shedlock-lock-at-most-for: PT10M
integration:
  case-management:
    base-url: http://case-management.url
  citizen:
    base-url: http://citizen.url
  eventlog:
    base-url: http://eventlog.url
  open-e:
    base-url: http://opene.url
    password: somePassword
    username: someUsername
    callback:
      internal-base-url: http://opene.url/callback/internal
      external-base-url: http://opene.url/callback/external
      external-password: somePassword
      internal-password: somePassword
      username: someUsername
  party:
    base-url: http://party.url
  support-management:
    base-url: http://support-management.url

spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6.4:///
  flyway:
    enabled: true
  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          schema-generation:
            script:
              append: false
      jakarta:
        persistence:
          schema-generation:
            create-source: metadata
            database:
              action: update
            scripts:
              action: create
              create-target: target/database/generated-schema.sql
  security:
    oauth2:
      client:
        provider:
          citizen:
            token-uri: http://localhost:${wiremock.server.port:}/api-gateway/token
          case-management:
            token-uri: http://localhost:${wiremock.server.port:}/api-gateway/token
          eventlog:
            token-uri: http://localhost:${wiremock.server.port:}/api-gateway/token
          party:
            token-uri: http://localhost:${wiremock.server.port:}/api-gateway/token
          support-management:
            token-uri: http://localhost:${wiremock.server.port:}/api-gateway/token
        registration:
          citizen:
            client-id: the-client-id
            client-secret: the-client-secret
          case-management:
            client-id: the-client-id
            client-secret: the-client-secret
          eventlog:
            client-id: the-client-id
            client-secret: the-client-secret
          party:
            client-id: the-client-id
            client-secret: the-client-secret
          support-management:
            client-id: the-client-id
            client-secret: the-client
