scheduler:
  eventlog:
    cron: "-"
    name: "eventlog"
    municipalityId: 123
    shedlock-lock-at-most-for: PT10M
    maximum-execution-time: PT10M
    clock-skew: PT5S
cache:
  isprod: true
  scheduled:
    name: "cache_job"
    cron: "-"
    shedlock-lock-at-most-for: PT10M
    maximum-execution-time: PT10M
integration:
  case-management:
    base-url: http://case-management.url
  eventlog:
    base-url: http://eventlog.url
  oep-integrator:
    base-url: http://oep-integrator.url
  party:
    base-url: http://party.url
  support-management:
    base-url: http://support-management.url
  case-data:
    base-url: http://case-data.url
    namespaces:
      - CASE_STATUS
      - CASE_DATA


spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6.4:///
  flyway:
    enabled: true
  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          schema-generation:
            script:
              append: false
      jakarta:
        persistence:
          schema-generation:
            create-source: metadata
            database:
              action: update
            scripts:
              action: create
              create-target: target/database/generated-schema.sql
  security:
    oauth2:
      client:
        provider:
          case-management:
            token-uri: http://localhost:${wiremock.server.port:}/api-gateway/token
          eventlog:
            token-uri: http://localhost:${wiremock.server.port:}/api-gateway/token
          party:
            token-uri: http://localhost:${wiremock.server.port:}/api-gateway/token
          support-management:
            token-uri: http://localhost:${wiremock.server.port:}/api-gateway/token
          oep-integrator:
            token-uri: http://localhost:${wiremock.server.port:}/api-gateway/token
          case-data:
            token-uri: http://localhost:${wiremock.server.port:}/api-gateway/token
        registration:
          case-management:
            client-id: the-client-id
            client-secret: the-client-secret
          eventlog:
            client-id: the-client-id
            client-secret: the-client-secret
          party:
            client-id: the-client-id
            client-secret: the-client-secret
          support-management:
            client-id: the-client-id
            client-secret: the-client
          oep-integrator:
            client-id: the-client-id
            client-secret: the-client-secret
          case-data:
            client-id: the-client-id
            client-secret: the-client-secret

#----------------------------------------
# Search role properties
#----------------------------------------
sm-status-search:
  roles:
    2281:
      MY_NAMESPACE: MY_ROLE
      MY_NAMESPACE2: MY_ROLE2
