integration:
  citizen:
    connectTimeout: 5
    readTimeout: 30
  case-management:
    connectTimeout: 5
    readTimeout: 30
  eventlog:
    connectTimeout: 5
    readTimeout: 30
  open-e:
    connectTimeout: 5
    readTimeout: 30
  party:
    connectTimeout: 5
    readTimeout: 30
  support-management:
    connectTimeout: 5
    readTimeout: 30

openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'
spring:
  application:
    name: api-case-status
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  flyway:
    enabled: false
  security:
    oauth2:
      client:
        registration:
          citizen:
            authorization-grant-type: client_credentials
            provider: citizen
          case-management:
            authorization-grant-type: client_credentials
            provider: case-management
          eventlog:
            authorization-grant-type: client_credentials
            provider: eventlog
          party:
            authorization-grant-type: client_credentials
            provider: party
          support-management:
            authorization-grant-type: client_credentials
            provider: support-management
#----------------------------------------
# Circuit breakers
#----------------------------------------
resilience4j:
  circuitbreaker:
    instances:
      case-management:
        ignoreExceptions: se.sundsvall.dept44.exception.ClientProblem
logbook:
  body-filters:
    x-path:
      - key: '//EncodedData[string-length(text()) > 0]'
        value: '[base64]'
