scheduler:
  eventlog:
    cron: "-"
    name: "eventlog"
    municipalityId: 123
    shedlock-lock-at-most-for: PT10M
    maximum-execution-time: PT10M
    clock-skew: PT5S
cache:
  isprod: false
  scheduled:
    name: "cache_job"
    cron: "-"
    shedlock-lock-at-most-for: PT10M
    maximum-execution-time: PT10M
integration:
  case-management:
    base-url: http://localhost:${wiremock.server.port}/casemanagement
  eventlog:
    base-url: http://localhost:${wiremock.server.port}/eventlog
  oep-integrator:
    base-url: http://localhost:${wiremock.server.port}/oep-integrator
  party:
    base-url: http://localhost:${wiremock.server.port}/party
  support-management:
    base-url: http://localhost:${wiremock.server.port}/supportmanagement
  case-data:
    base-url: http://localhost:${wiremock.server.port}/case-data
    namespaces:
      - NAMESPACE_1
      - NAMESPACE_2

spring:
  main:
    banner-mode: 'off'
  flyway:
    enabled: true
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6.4:///
  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          schema-generation:
            script:
              append: false
      jakarta:
        persistence:
          schema-generation:
            create-source: metadata
            database:
              action: update
            scripts:
              action: create
              create-target: target/database/generated-schema.sql
  security:
    oauth2:
      client:
        provider:
          case-management:
            token-uri: http://localhost:${wiremock.server.port:}/token
          eventlog:
            token-uri: http://localhost:${wiremock.server.port:}/token
          party:
            token-uri: http://localhost:${wiremock.server.port:}/token
          support-management:
            token-uri: http://localhost:${wiremock.server.port:}/token
          oep-integrator:
            token-uri: http://localhost:${wiremock.server.port:}/token
          case-data:
            token-uri: http://localhost:${wiremock.server.port:}/token
        registration:
          case-management:
            client-id: the-client-id
            client-secret: the-client-secret
          eventlog:
            client-id: the-client-id
            client-secret: the-client
          party:
            client-id: the-client-id
            client-secret: the-client-secret
          support-management:
            client-id: the-client-id
            client-secret: the-client
          oep-integrator:
            client-id: the-client-id
            client-secret: the-client-secret
          case-data:
            client-id: the-client-id
            client-secret: the-client-secret
