integration:
  citizen:
    connectTimeout: 5
    readTimeout: 30
  case-management:
    connectTimeout: 5
    readTimeout: 30
  open-e:
    connectTimeout: 5
    readTimeout: 30
  incident:
    connectTimeout: 5
    readTimeout: 30

openapi:
  name: api-case-status
  title: CaseStatus
  version: 2.0
spring:
  application:
    name: api-case-status
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  flyway:
    enabled: false
  security:
    oauth2:
      client:
        registration:
          citizen:
            authorization-grant-type: client_credentials
            provider: citizen
          case-management:
            authorization-grant-type: client_credentials
            provider: case-management
          incident:
            authorization-grant-type: client_credentials
            provider: incident
logbook:
  body-filters:
    x-path:
      - key: '//EncodedData[string-length(text()) > 0]'
        value: '[base64]'
