cache:
  isprod: false
  scheduled:
    fixedrate: 1d
    initialdelay: 1m
    shedlock-lock-at-most-for: PT10M
integration:
  case-management:
    base-url: http://localhost:${wiremock.server.port}/casemanagement
    oauth2:
      client-id: dummy
      client-secret: dummy
      token-uri: http://localhost:${wiremock.server.port}/token
  citizen:
    base-url: http://localhost:${wiremock.server.port}/citizen
    oauth2:
      client-id: dummy
      client-secret: dummy
      token-uri: http://localhost:${wiremock.server.port}/token
  db:
    case-status:
      driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
      password: ''
      # Using 4 '/' is a workaround to this bug https://github.com/testcontainers/testcontainers-java/issues/4121
      url: jdbc:tc:mariadb:10.6:////ms-casestatus
      username: sa
  incident:
    base-url: http://localhost:${wiremock.server.port}/incident
    oauth2:
      client-id: dummy
      client-secret: dummy
      token-uri: http://localhost:${wiremock.server.port}/token
  open-e:
    base-url: localhost
    basic-auth:
      password: dummy
      username: dummy
    port: ${wiremock.server.port}
    scheme: http
spring:
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: verify
  main:
    banner-mode: 'off'
  sql:
    init:
      mode: never
